In [12]:
import pandas as pd
import numpy as np
df=pd.read_csv('./Dataset_Model.csv')

In [19]:
df.head(2)

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Pedestrian_Crossing-Human_Control,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site
0,0,3,2,1,Single carriageway,30,None within 50 metres,Snowing with high winds,Snow,None
1,1,3,1,1,Single carriageway,60,None within 50 metres,Fine without high winds,Wet/Damp,None

In [20]:
df.shape

(50000, 10)

In [22]:
df1 = df.drop("Unnamed: 0", axis=1)
df1.head(1)

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Pedestrian_Crossing-Human_Control,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site
0,3,2,1,Single carriageway,30,None within 50 metres,Snowing with high winds,Snow,None

In [29]:
Road_Type_dummies = pd.get_dummies(df1["Road_Type"])

In [30]:
Road_Type_dummies.head(5)

,Dual carriageway,One way street,Roundabout,Single carriageway,Slip road,Unknown
0,0,0,0,1,0,0
1,0,0,0,1,0,0
2,0,0,1,0,0,0
3,0,0,0,1,0,0
4,0,0,0,1,0,0

In [43]:
df2 = pd.concat([df1, Road_Type_dummies2], axis=1)

In [45]:
df2 = df2.drop("Pedestrian_Crossing-Human_Control", axis=1)

In [46]:
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,3,2,1,Single carriageway,30,Snowing with high winds,Snow,None,0,0,1
1,3,1,1,Single carriageway,60,Fine without high winds,Wet/Damp,None,0,0,1
2,3,1,1,Roundabout,30,Fine without high winds,Dry,None,0,0,1
3,3,1,1,Single carriageway,40,Fine without high winds,Dry,None,0,0,1
4,3,1,1,Single carriageway,30,Fine without high winds,Dry,None,0,0,1

In [37]:
df2 = df2.drop("Road_Type", axis=1)

In [39]:
Road_Type_dummies2 = pd.get_dummies(df1["Pedestrian_Crossing-Human_Control"])

In [42]:
Road_Type_dummies2.head(5)

,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,0,0,1
1,0,0,1
2,0,0,1
3,0,0,1
4,0,0,1

In [49]:
Road_Type_dummies3 = pd.get_dummies(df1["Road_Surface_Conditions"])

In [50]:
df2 = df2.drop("Road_Surface_Conditions", axis=1)

In [51]:
Road_Type_dummies3 = pd.get_dummies(df1["Special_Conditions_at_Site"])

In [52]:
df2 = df2.drop("Special_Conditions_at_Site", axis=1)

In [53]:
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Weather_Conditions,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,3,2,1,30,Snowing with high winds,0,0,1
1,3,1,1,60,Fine without high winds,0,0,1
2,3,1,1,30,Fine without high winds,0,0,1
3,3,1,1,40,Fine without high winds,0,0,1
4,3,1,1,30,Fine without high winds,0,0,1

In [ ]:
df

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
y=df['Accident_Severity']

In [8]:
y.head()

0    3
1    3
2    3
3    3
4    3
Name: Accident_Severity, dtype: int64

In [9]:
x=df.drop('Accident_Severity',axis=1)

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1000)

In [11]:
x_train

,Unnamed: 0,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Pedestrian_Crossing-Human_Control,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site
18564,18564,1,1,Single carriageway,30,None within 50 metres,Fine without high winds,Dry,None
13591,13591,5,6,Dual carriageway,70,None within 50 metres,Fine without high winds,Wet/Damp,None
13214,13214,1,2,Dual carriageway,70,None within 50 metres,Fine without high winds,Dry,None
24868,24868,2,1,Roundabout,40,None within 50 metres,Fine without high winds,Dry,None
44344,44344,2,1,Single carriageway,30,None within 50 metres,Fine without high winds,Dry,None
...,...,...,...,...,...,...,...,...,...
48379,48379,2,1,Single carriageway,30,None within 50 metres,Fine without high winds,Dry,None
3776,3776,2,1,Single carriageway,30,None within 50 metres,Fine with high winds,Dry,None
6215,6215,2,1,Single carriageway,50,None within 50 metres,Other,Wet/Damp,None
4695,4695,2,3,Roundabout,40,None within 50 metres,Fine without high winds,Wet/Damp,None
42419,42419,1,1,Roundabout,50,None within 50 metres,Fine without high winds,Dry,Auto traffic singal out

In [47]:
df2 = df2.drop("Road_Type", axis=1)

In [48]:
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,3,2,1,30,Snowing with high winds,Snow,None,0,0,1
1,3,1,1,60,Fine without high winds,Wet/Damp,None,0,0,1
2,3,1,1,30,Fine without high winds,Dry,None,0,0,1
3,3,1,1,40,Fine without high winds,Dry,None,0,0,1
4,3,1,1,30,Fine without high winds,Dry,None,0,0,1

In [54]:
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Weather_Conditions,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,3,2,1,30,Snowing with high winds,0,0,1
1,3,1,1,60,Fine without high winds,0,0,1
2,3,1,1,30,Fine without high winds,0,0,1
3,3,1,1,40,Fine without high winds,0,0,1
4,3,1,1,30,Fine without high winds,0,0,1

In [55]:
Road_Type_dummies = pd.get_dummies(df1["Road_Type"])

In [56]:
df2 = pd.concat([df1, Road_Type_dummies], axis=1)

In [57]:
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Pedestrian_Crossing-Human_Control,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Dual carriageway,One way street,Roundabout,Single carriageway,Slip road,Unknown
0,3,2,1,Single carriageway,30,None within 50 metres,Snowing with high winds,Snow,None,0,0,0,1,0,0
1,3,1,1,Single carriageway,60,None within 50 metres,Fine without high winds,Wet/Damp,None,0,0,0,1,0,0
2,3,1,1,Roundabout,30,None within 50 metres,Fine without high winds,Dry,None,0,0,1,0,0,0
3,3,1,1,Single carriageway,40,None within 50 metres,Fine without high winds,Dry,None,0,0,0,1,0,0
4,3,1,1,Single carriageway,30,None within 50 metres,Fine without high winds,Dry,None,0,0,0,1,0,0

In [58]:
df2 = df2.drop("Road_Type", axis=1)
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Pedestrian_Crossing-Human_Control,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Dual carriageway,One way street,Roundabout,Single carriageway,Slip road,Unknown
0,3,2,1,30,None within 50 metres,Snowing with high winds,Snow,None,0,0,0,1,0,0
1,3,1,1,60,None within 50 metres,Fine without high winds,Wet/Damp,None,0,0,0,1,0,0
2,3,1,1,30,None within 50 metres,Fine without high winds,Dry,None,0,0,1,0,0,0
3,3,1,1,40,None within 50 metres,Fine without high winds,Dry,None,0,0,0,1,0,0
4,3,1,1,30,None within 50 metres,Fine without high winds,Dry,None,0,0,0,1,0,0

In [59]:
Road_Type_dummies5 = pd.get_dummies(df1["Weather_Conditions"])
df2 = pd.concat([df1, Road_Type_dummies5], axis=1)
df2 = df2.drop("Weather_Conditions", axis=1)
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Pedestrian_Crossing-Human_Control,Road_Surface_Conditions,Special_Conditions_at_Site,Fine with high winds,Fine without high winds,Fog or mist,Other,Raining with high winds,Raining without high winds,Snowing with high winds,Snowing without high winds,Unknown
0,3,2,1,Single carriageway,30,None within 50 metres,Snow,None,0,0,0,0,0,0,1,0,0
1,3,1,1,Single carriageway,60,None within 50 metres,Wet/Damp,None,0,1,0,0,0,0,0,0,0
2,3,1,1,Roundabout,30,None within 50 metres,Dry,None,0,1,0,0,0,0,0,0,0
3,3,1,1,Single carriageway,40,None within 50 metres,Dry,None,0,1,0,0,0,0,0,0,0
4,3,1,1,Single carriageway,30,None within 50 metres,Dry,None,0,1,0,0,0,0,0,0,0

In [60]:
df2 = df2.drop("Road_Type", axis=1)
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Pedestrian_Crossing-Human_Control,Road_Surface_Conditions,Special_Conditions_at_Site,Fine with high winds,Fine without high winds,Fog or mist,Other,Raining with high winds,Raining without high winds,Snowing with high winds,Snowing without high winds,Unknown
0,3,2,1,30,None within 50 metres,Snow,None,0,0,0,0,0,0,1,0,0
1,3,1,1,60,None within 50 metres,Wet/Damp,None,0,1,0,0,0,0,0,0,0
2,3,1,1,30,None within 50 metres,Dry,None,0,1,0,0,0,0,0,0,0
3,3,1,1,40,None within 50 metres,Dry,None,0,1,0,0,0,0,0,0,0
4,3,1,1,30,None within 50 metres,Dry,None,0,1,0,0,0,0,0,0,0

In [63]:
Road_Type_dummies7 = pd.get_dummies(df1["Road_Surface_Conditions"])
df3 = pd.concat([df1, Road_Type_dummies7], axis=1)
df3 = df2.drop("Road_Surface_Conditions", axis=1)
df3.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Weather_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,3,2,1,Single carriageway,30,Snowing with high winds,None,0,0,1
1,3,1,1,Single carriageway,60,Fine without high winds,None,0,0,1
2,3,1,1,Roundabout,30,Fine without high winds,None,0,0,1
3,3,1,1,Single carriageway,40,Fine without high winds,None,0,0,1
4,3,1,1,Single carriageway,30,Fine without high winds,None,0,0,1

In [64]:
Road_Type_dummies8 = pd.get_dummies(df1["Road_Type"])
df4 = pd.concat([df1, Road_Type_dummies8], axis=1)
df4 = df3.drop("Road_Type", axis=1)
df4.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Weather_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,3,2,1,30,Snowing with high winds,None,0,0,1
1,3,1,1,60,Fine without high winds,None,0,0,1
2,3,1,1,30,Fine without high winds,None,0,0,1
3,3,1,1,40,Fine without high winds,None,0,0,1
4,3,1,1,30,Fine without high winds,None,0,0,1

In [65]:
df2.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,3,2,1,Single carriageway,30,Snowing with high winds,Snow,None,0,0,1
1,3,1,1,Single carriageway,60,Fine without high winds,Wet/Damp,None,0,0,1
2,3,1,1,Roundabout,30,Fine without high winds,Dry,None,0,0,1
3,3,1,1,Single carriageway,40,Fine without high winds,Dry,None,0,0,1
4,3,1,1,Single carriageway,30,Fine without high winds,Dry,None,0,0,1

In [66]:
df2.to_csv('xyz.csv')

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('./xyz.csv')
df.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres
0,0,3,2,1,Single carriageway,30,Snowing with high winds,Snow,None,0,0,1
1,1,3,1,1,Single carriageway,60,Fine without high winds,Wet/Damp,None,0,0,1
2,2,3,1,1,Roundabout,30,Fine without high winds,Dry,None,0,0,1
3,3,3,1,1,Single carriageway,40,Fine without high winds,Dry,None,0,0,1
4,4,3,1,1,Single carriageway,30,Fine without high winds,Dry,None,0,0,1

In [4]:
Road_Type_dummies = pd.get_dummies(df["Road_Surface_Conditions"])
df2 = pd.concat([df, Road_Type_dummies], axis=1)

df2.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,Flood (Over 3cm of water),Frost/Ice,Normal,Snow,Wet/Damp
0,0,3,2,1,Single carriageway,30,Snowing with high winds,Snow,None,0,0,1,0,0,0,0,1,0
1,1,3,1,1,Single carriageway,60,Fine without high winds,Wet/Damp,None,0,0,1,0,0,0,0,0,1
2,2,3,1,1,Roundabout,30,Fine without high winds,Dry,None,0,0,1,1,0,0,0,0,0
3,3,3,1,1,Single carriageway,40,Fine without high winds,Dry,None,0,0,1,1,0,0,0,0,0
4,4,3,1,1,Single carriageway,30,Fine without high winds,Dry,None,0,0,1,1,0,0,0,0,0

In [5]:
df2 = df2.drop("Road_Surface_Conditions", axis=1)

In [6]:
df2.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Weather_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,Flood (Over 3cm of water),Frost/Ice,Normal,Snow,Wet/Damp
0,0,3,2,1,Single carriageway,30,Snowing with high winds,None,0,0,1,0,0,0,0,1,0
1,1,3,1,1,Single carriageway,60,Fine without high winds,None,0,0,1,0,0,0,0,0,1
2,2,3,1,1,Roundabout,30,Fine without high winds,None,0,0,1,1,0,0,0,0,0
3,3,3,1,1,Single carriageway,40,Fine without high winds,None,0,0,1,1,0,0,0,0,0
4,4,3,1,1,Single carriageway,30,Fine without high winds,None,0,0,1,1,0,0,0,0,0

In [7]:
Road_Type_dummies2 = pd.get_dummies(df2["Road_Type"])
df3 = pd.concat([df2, Road_Type_dummies2], axis=1)

df3.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Road_Type,Speed_limit,Weather_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,...,Frost/Ice,Normal,Snow,Wet/Damp,Dual carriageway,One way street,Roundabout,Single carriageway,Slip road,Unknown
0,0,3,2,1,Single carriageway,30,Snowing with high winds,None,0,0,...,0,0,1,0,0,0,0,1,0,0
1,1,3,1,1,Single carriageway,60,Fine without high winds,None,0,0,...,0,0,0,1,0,0,0,1,0,0
2,2,3,1,1,Roundabout,30,Fine without high winds,None,0,0,...,0,0,0,0,0,0,1,0,0,0
3,3,3,1,1,Single carriageway,40,Fine without high winds,None,0,0,...,0,0,0,0,0,0,0,1,0,0
4,4,3,1,1,Single carriageway,30,Fine without high winds,None,0,0,...,0,0,0,0,0,0,0,1,0,0

In [8]:
df3 = df3.drop("Road_Type", axis=1)

In [9]:
df3.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Weather_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres,...,Frost/Ice,Normal,Snow,Wet/Damp,Dual carriageway,One way street,Roundabout,Single carriageway,Slip road,Unknown
0,0,3,2,1,30,Snowing with high winds,None,0,0,1,...,0,0,1,0,0,0,0,1,0,0
1,1,3,1,1,60,Fine without high winds,None,0,0,1,...,0,0,0,1,0,0,0,1,0,0
2,2,3,1,1,30,Fine without high winds,None,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,3,3,1,1,40,Fine without high winds,None,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4,4,3,1,1,30,Fine without high winds,None,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [11]:
Road_Type_dummies3 = pd.get_dummies(df3["Weather_Conditions"])
df4 = pd.concat([df3, Road_Type_dummies3], axis=1)

df4.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Weather_Conditions,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres,...,Unknown,Fine with high winds,Fine without high winds,Fog or mist,Other,Raining with high winds,Raining without high winds,Snowing with high winds,Snowing without high winds,Unknown
0,0,3,2,1,30,Snowing with high winds,None,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,1,3,1,1,60,Fine without high winds,None,0,0,1,...,0,0,1,0,0,0,0,0,0,0
2,2,3,1,1,30,Fine without high winds,None,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,3,3,1,1,40,Fine without high winds,None,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,4,3,1,1,30,Fine without high winds,None,0,0,1,...,0,0,1,0,0,0,0,0,0,0

In [12]:
df4 = df4.drop("Weather_Conditions", axis=1)

In [13]:
df4.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,...,Unknown,Fine with high winds,Fine without high winds,Fog or mist,Other,Raining with high winds,Raining without high winds,Snowing with high winds,Snowing without high winds,Unknown
0,0,3,2,1,30,None,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1,1,3,1,1,60,None,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
2,2,3,1,1,30,None,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0
3,3,3,1,1,40,None,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0
4,4,3,1,1,30,None,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0

In [14]:
Road_Type_dummies4 = pd.get_dummies(df4["Special_Conditions_at_Site"])
df5 = pd.concat([df4, Road_Type_dummies4], axis=1)

df5.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Special_Conditions_at_Site,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,...,Snowing without high winds,Unknown,Auto traffic signal partly defective,Auto traffic singal out,Mud,None,Ol or diesel,Permanent sign or marking defective or obscured,Road surface defective,Roadworks
0,0,3,2,1,30,None,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,1,3,1,1,60,None,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
2,2,3,1,1,30,None,0,0,1,1,...,0,0,0,0,0,1,0,0,0,0
3,3,3,1,1,40,None,0,0,1,1,...,0,0,0,0,0,1,0,0,0,0
4,4,3,1,1,30,None,0,0,1,1,...,0,0,0,0,0,1,0,0,0,0

In [16]:
df5 = df5.drop("Special_Conditions_at_Site", axis=1)

In [17]:
df5.head()

,Unnamed: 0,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,Flood (Over 3cm of water),...,Snowing without high winds,Unknown,Auto traffic signal partly defective,Auto traffic singal out,Mud,None,Ol or diesel,Permanent sign or marking defective or obscured,Road surface defective,Roadworks
0,0,3,2,1,30,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1,1,3,1,1,60,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
2,2,3,1,1,30,0,0,1,1,0,...,0,0,0,0,0,1,0,0,0,0
3,3,3,1,1,40,0,0,1,1,0,...,0,0,0,0,0,1,0,0,0,0
4,4,3,1,1,30,0,0,1,1,0,...,0,0,0,0,0,1,0,0,0,0

In [18]:
df5 = df5.drop("Unnamed: 0", axis=1)
df5.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,Flood (Over 3cm of water),Frost/Ice,...,Snowing without high winds,Unknown,Auto traffic signal partly defective,Auto traffic singal out,Mud,None,Ol or diesel,Permanent sign or marking defective or obscured,Road surface defective,Roadworks
0,3,2,1,30,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,3,1,1,60,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,3,1,1,30,0,0,1,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,3,1,1,40,0,0,1,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,3,1,1,30,0,0,1,1,0,0,...,0,0,0,0,0,1,0,0,0,0

In [19]:
df5.to_csv('Model.csv')

In [21]:
y=df5['Accident_Severity']

In [22]:
x=df5.drop('Accident_Severity', axis =1)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.1,random_state=1000)

In [25]:
x_train

,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,Flood (Over 3cm of water),Frost/Ice,Normal,...,Snowing without high winds,Unknown,Auto traffic signal partly defective,Auto traffic singal out,Mud,None,Ol or diesel,Permanent sign or marking defective or obscured,Road surface defective,Roadworks
18564,1,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13591,5,6,70,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13214,1,2,70,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24868,2,1,40,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
44344,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48379,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3776,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6215,2,1,50,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4695,2,3,40,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
42419,1,1,50,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [26]:
x_test

,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,Flood (Over 3cm of water),Frost/Ice,Normal,...,Snowing without high winds,Unknown,Auto traffic signal partly defective,Auto traffic singal out,Mud,None,Ol or diesel,Permanent sign or marking defective or obscured,Road surface defective,Roadworks
9170,2,1,30,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
48685,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
31128,2,2,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
39393,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24265,2,3,30,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46455,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
49070,2,1,70,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
40847,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14577,1,1,30,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
11227,3,4,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [27]:
y_test

9170     3
48685    3
31128    3
39393    2
24265    3
        ..
46455    3
49070    3
40847    3
14577    3
11227    3
Name: Accident_Severity, Length: 5000, dtype: int64

In [28]:
from sklearn.linear_model import LogisticRegression

In [43]:
LogisticRegression(solver='lbfgs', max_iter=1000000)

LogisticRegression(max_iter=1000000)

In [45]:
gnb = LogisticRegression()

In [46]:
gnb.fit(x_train,y_train)

C:\Users\sonis\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [51]:
score = LogisticRegression.score(x_test, y_test)
print('Test Accuracy Score', score)

TypeError: score() missing 1 required positional argument: 'y'

In [53]:
y = y_train.values.ravel()

In [55]:
y = y_train.values.ravel()
score = LogisticRegression.score(x_test, y_test)
print('Test Accuracy Score', score)

TypeError: score() missing 1 required positional argument: 'y'

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_test)

ValueError: Found input variables with inconsistent numbers of samples: [45000, 5000]

In [58]:
model=LogisticRegression()

In [60]:
model.fit(x_train,y_train)

C:\Users\sonis\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [61]:
model.score?

In [62]:
model.score(x_train,y_train)

0.8660666666666667

In [64]:
model.predict(x_test)

array([3, 3, 3, ..., 3, 3, 3], dtype=int64)

In [66]:
y_pred=model.predict(x_test)
y_pred == y_test

9170      True
48685     True
31128     True
39393    False
24265     True
         ...
46455     True
49070     True
40847     True
14577     True
11227     True
Name: Accident_Severity, Length: 5000, dtype: bool

In [67]:
import numpy as np

In [68]:
np.mean(y_pred==y_test)

0.865

In [70]:
x_train

,Number_of_Vehicles,Number_of_Casualties,Speed_limit,Control by other authorised person,Control by school crossing patrol,None within 50 metres,Dry,Flood (Over 3cm of water),Frost/Ice,Normal,...,Snowing without high winds,Unknown,Auto traffic signal partly defective,Auto traffic singal out,Mud,None,Ol or diesel,Permanent sign or marking defective or obscured,Road surface defective,Roadworks
18564,1,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13591,5,6,70,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13214,1,2,70,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
24868,2,1,40,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
44344,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48379,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3776,2,1,30,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
6215,2,1,50,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4695,2,3,40,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
42419,1,1,50,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [71]:
model.score(x_test,y_test)

0.865

In [72]:
LogisticRegression?

In [77]:
model=LogisticRegression(max_iter=100000)

In [78]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=100000)

In [81]:
cross_val_score(model,x_train,y_train,cv=5,scoring="accuracy")

NameError: name 'cross_val_score' is not defined